# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.subsets_cpp <- function(d) {
    .Call('_satdad_subsets_cpp', PACKAGE = 'satdad', d)
}

.sort_sub_cpp <- function(sub) {
    .Call('_satdad_sort_sub_cpp', PACKAGE = 'satdad', sub)
}

.generate_asy_sub_cpp <- function(d, sub) {
    .Call('_satdad_generate_asy_sub_cpp', PACKAGE = 'satdad', d, sub)
}

.find_missing_indices_cpp <- function(d, sub) {
    .Call('_satdad_find_missing_indices_cpp', PACKAGE = 'satdad', d, sub)
}

.algo21_numMat_cpp <- function(n, d, alpha) {
    .Call('_satdad_algo21_numMat_cpp', PACKAGE = 'satdad', n, d, alpha)
}

.algo22_numMat_cpp <- function(n, d, sub, dep, asy) {
    .Call('_satdad_algo22_numMat_cpp', PACKAGE = 'satdad', n, d, sub, dep, asy)
}

.ellmevlogv_cpp <- function(v, d, sub, dep, asy) {
    .Call('_satdad_ellmevlogv_cpp', PACKAGE = 'satdad', v, d, sub, dep, asy)
}

.ratio_diff_pmevlogv_cpp <- function(v, d, sub, dep, asy) {
    .Call('_satdad_ratio_diff_pmevlogv_cpp', PACKAGE = 'satdad', v, d, sub, dep, asy)
}

.ratio_diff_pmevlogm_cpp <- function(v, d, sub, dep, asy) {
    .Call('_satdad_ratio_diff_pmevlogm_cpp', PACKAGE = 'satdad', v, d, sub, dep, asy)
}

.ratio_diff_pmevlogv_marv_cpp <- function(v, d, sub, dep, asy, mar) {
    .Call('_satdad_ratio_diff_pmevlogv_marv_cpp', PACKAGE = 'satdad', v, d, sub, dep, asy, mar)
}

.ratio_diff_pmevlogm_marv_cpp <- function(v, d, sub, dep, asy, mar) {
    .Call('_satdad_ratio_diff_pmevlogm_marv_cpp', PACKAGE = 'satdad', v, d, sub, dep, asy, mar)
}

.ratio_diff_pmevlogv_marm_cpp <- function(v, d, sub, dep, asy, mar) {
    .Call('_satdad_ratio_diff_pmevlogv_marm_cpp', PACKAGE = 'satdad', v, d, sub, dep, asy, mar)
}

.ratio_diff_pmevlogm_marm_cpp <- function(v, d, sub, dep, asy, mar) {
    .Call('_satdad_ratio_diff_pmevlogm_marm_cpp', PACKAGE = 'satdad', v, d, sub, dep, asy, mar)
}

.ellmevlogm_cpp <- function(v, d, sub, dep, asy) {
    .Call('_satdad_ellmevlogm_cpp', PACKAGE = 'satdad', v, d, sub, dep, asy)
}

.ecdsmevlog_cpp <- function(d, sub, dep, asy, ind) {
    .Call('_satdad_ecdsmevlog_cpp', PACKAGE = 'satdad', d, sub, dep, asy, ind)
}

.tsicdsmevlog_list_cpp <- function(N, d, sub, dep, asy, L) {
    .Call('_satdad_tsicdsmevlog_list_cpp', PACKAGE = 'satdad', N, d, sub, dep, asy, L)
}

.tsicdsmevlog_empty_cpp <- function(N, d, sub, dep, asy) {
    .Call('_satdad_tsicdsmevlog_empty_cpp', PACKAGE = 'satdad', N, d, sub, dep, asy)
}

.ellEmp_cpp <- function(kvec, x, sample) {
    .Call('_satdad_ellEmp_cpp', PACKAGE = 'satdad', kvec, x, sample)
}

.rankbar_cpp <- function(x, k) {
    .Call('_satdad_rankbar_cpp', PACKAGE = 'satdad', x, k)
}

.ratioall_cpp <- function(R) {
    .Call('_satdad_ratioall_cpp', PACKAGE = 'satdad', R)
}

.ratioallsobol_cpp <- function(R) {
    .Call('_satdad_ratioallsobol_cpp', PACKAGE = 'satdad', R)
}

.prodmin_cpp <- function(R) {
    .Call('_satdad_prodmin_cpp', PACKAGE = 'satdad', R)
}

.prodprod_cpp <- function(R) {
    .Call('_satdad_prodprod_cpp', PACKAGE = 'satdad', R)
}

